/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card/Card.vue')['default']
    Card2: typeof import('./src/components/card/Card2.vue')['default']
    CheckboxList: typeof import('./src/components/keepalive/CheckboxList.vue')['default']
    CompA: typeof import('./src/components/componet/CompA.vue')['default']
    CompB: typeof import('./src/components/componet/CompB.vue')['default']
    Counter: typeof import('./src/components/keepalive/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('./src/components/todo/Footer.vue')['default']
    Header: typeof import('./src/components/todo/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    List: typeof import('./src/components/todo/List.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    Rate: typeof import('./src/components/rating/Rate.vue')['default']
    Rating: typeof import('./src/components/rating/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./src/components/Task/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/Task/TaskList.vue')['default']
    TextInput: typeof import('./src/components/keepalive/TextInput.vue')['default']
    Timer: typeof import('./src/components/keepalive/Timer.vue')['default']
    UserCard: typeof import('./src/components/user/UserCard.vue')['default']
  }
}
