/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/card/Card.vue')['default']
    Card2: typeof import('./components/card/Card2.vue')['default']
    CheckboxList: typeof import('./components/keepalive/CheckboxList.vue')['default']
    CompA: typeof import('./components/componet/CompA.vue')['default']
    CompB: typeof import('./components/componet/CompB.vue')['default']
    Counter: typeof import('./components/keepalive/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./components/todo/Footer.vue')['default']
    Header: typeof import('./components/todo/Header.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    List: typeof import('./components/todo/List.vue')['default']
    Message: typeof import('./components/Message/Message.vue')['default']
    Rate: typeof import('./components/rating/Rate.vue')['default']
    Rating: typeof import('./components/rating/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./components/Task/TaskItem.vue')['default']
    TaskList: typeof import('./components/Task/TaskList.vue')['default']
    TextInput: typeof import('./components/keepalive/TextInput.vue')['default']
    Timer: typeof import('./components/keepalive/Timer.vue')['default']
    UserCard: typeof import('./components/user/UserCard.vue')['default']
  }
}
